export const CHANGE_SEARCH_STRING = 'CHANGE_SEARCH_STRING';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REG_REQUEST = 'REG_REQUEST';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_FAILURE = 'REG_FAILURE';

export const CREATE_MODEL_OPENED = 'CREATE_MODEL_OPENED';
export const EDIT_MODEL_OPENED = 'EDIT_MODEL_OPENED';

export const GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAILURE = 'GET_CONTACT_FAILURE';

export const GET_PART_CONTACT_REQUEST = 'GET_PART_CONTACT_REQUEST';
export const GET_PART_CONTACT_SUCCESS = 'GET_PART_CONTACT_SUCCESS';
export const GET_PART_CONTACT_FAILURE = 'GET_PART_CONTACT_FAILURE';

export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE';

export const CHANGE_CONTACT_REQUEST = 'CHANGE_CONTACT_REQUEST';
export const CHANGE_CONTACT_SUCCESS = 'CHANGE_CONTACT_SUCCESS';
export const CHANGE_CONTACT_FAILURE = 'CHANGE_CONTACT_FAILURE';

export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';

export const OPEN_DELETE_MODAL = 'OPEN_DELETE_MODAL';

export const SORT_CONTACT = 'SORT_CONTACT';

export const LOG_OUT = 'LOG_OUT';

export const CONTACTS_COUNT = 'CONTACTS_COUNT';

export const IS_REG_MODAL = 'IS_REG_MODAL';

export const CHANGE_SHOW_CONTACTS = 'CHANGE_SHOW_CONTACTS';

export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';

export const FILTER_MODAL_OPENED = 'FILTER_MODAL_OPENED';

export const FILTER_LEVEL_ADD = 'FILTER_LEVEL_ADD';
export const FILTER_LEVEL_REMOVE = 'FILTER_LEVEL_REMOVE';

export const FILTER_PROMOTER_ADD = 'FILTER_PROMOTER_ADD';
export const FILTER_PROMOTER_REMOVE = 'FILTER_PROMOTER_REMOVE';

export const FILTER_DECISION_ADD = 'FILTER_DECISION_ADD';
export const FILTER_DECISION_REMOVE = 'FILTER_DECISION_REMOVE';

export const COPY_FILTER = 'COPY_FILTER';
